spring:
  datasource:
    url: jdbc:mariadb://43.202.122.11:32006/maestro
    username: maestro
    password: okestro2018!
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
      data-locations: classpath:data-shop.sql

# JWT 설정
jwt:
  secret: dGhpc2lzYXZlcnlsb25nc2VjcmV0a2V5Zm9yand0dG9rZW5nZW5lcmF0aW9uYW5kdmFsaWRhdGlvbjEyMzQ1Njc4OTA=
  access-token-expiration: 1800000
  refresh-token-expiration: 604800000

minio:
  url: http://43.202.122.11:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket-name: my-bucket
  testcase-bucket-name: okestro-testcases

judge0:
  api-url: http://52.79.146.35:2358
  authn-token: 39BF5B3EBEE27083B51AA246888EB74970F12920EBBE92DF534F97F314D07608
  authz-token: 39BF5B3EBEE27083B51AA246888EB74970F12920EBBE92DF534F97F314D07608
  cpu-time-limit: 5
  memory-limit: 128000
  max-file-size: 4096
  max-retries: 30
  retry-delay-ms: 2000

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

# 로그 설정
logging:
  level:
    com.okestro.okestroonlinejudge: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
